name: CI-CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Check Project Files
        run: |
          echo "Checking project files..."
          ls

      - name: Validate HTML
        run: |
          if [ -f MusicPlayer.html ]; then
            echo "HTML file found."
          else
            echo "HTML file missing!"
            exit 1
          fi

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Deploy Message
        run: echo "Deployment successful"
